---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/recipes/index":
    get:
      summary: list recipes
      responses:
        '200':
          description: successful
  "/api/v1/recipes/create":
    post:
      summary: create recipe
      responses:
        '200':
          description: successful
  "/api/v1/show/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show recipe
      responses:
        '200':
          description: successful
  "/api/v1/destroy/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete recipe
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
